apiVersion: aws.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: aws-provider
spec:
  region: eu-west-3
  credentialsSecretRef:
    namespace: crossplane-system
    name: aws-creds
    key: key
